const constants = {
    CREATE_NEW_PROJECT: "CREATE_NEW_PROJECT",
    OPEN_PROJECT_DIALOG: "OPEN_PROJECT_DIALOG",
    CLOSE_PROJECT_DIALOG: "CLOSE_PROJECT_DIALOG",
    OPEN_PROJECT: "OPEN_PROJECT",
    IMPORT_FILES: "IMPORT_FILES",

    INSERT_SHOT: "INSERT_SHOT",
    UPDATE_PREVIEW: "UPDATE_PREVIEW",
}

export default constants